#!/bin/sh

cd /var/www/nfd/ && python app.py &

echo "Waiting until X11 settled..."
sleep 20

echo "Disabling Monitor Standby mode..."
xset -dpms
xset s noblank
xset s off

which unclutter 2>&1 >/dev/null
if [ $? -eq 0 ]; then
	echo "Hide mouse pointer..."
	unclutter &
fi

echo "Setting Google Chrome to fullscreen..."
xwit -move 0 0 -resize 1280 1024 -current